language: generic

os: linux
dist: focal
cache: packages
warnings_are_errors: false


before_install:
  - sudo apt-get install -y --no-install-recommends build-essential texlive-base texlive-extra-utils texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-sciencetexlive-xetex
  - sudo apt-get install -y pandoc

install: echo Installation step #do not remove this line!

script: make manual-git

after_success: tools/deploy.sh

notifications:
  email: false

