language: r

os: linux
dist: bionic
cache: packages
warnings_are_errors: false


before_install:
  - tlmgr update --self --repository http://mirror.ox.ac.uk/sites/ctan.org/systems/texlive/tlnet/
  - tlmgr install --repository http://mirror.ox.ac.uk/sites/ctan.org/systems/texlive/tlnet/ standalone showexpl imakeidx xpatch was context

install: echo Installation step #do not remove this line!

script: make manual-git

after_success: tools/deploy.sh

notifications:
  email: false

