language: generic

os: linux
dist: focal
cache: packages
warnings_are_errors: false


before_install:
  - sudo apt-get install -y build-essential texlive-xetex texlive-pictures texlive-science
  - sudo apt-get install -y pandoc context

install: echo Installation step #do not remove this line!

script: make manual-git

after_success: tools/deploy.sh

notifications:
  email: false

